name: NPM Publish

# This action will trigger everytime a release gets created
on:
  release:
    types: [created]

# Job will run on a ubuntu instance
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      # Setup node with version 14.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      # Run npm install to install project packages
      - run: npm install
      # npm build to build the project
      - run: npm run build
      # publish the files to NPM
      - run: npm publish --access public
      # for publishing, npm needs authorization. We add the NPM token to the environment which will take care of authorization to publish the package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
